language: node_js
node_js: 14.0.0
cache:
  directories:
  - node_modules
install:
- rm -rf docs/.vuepress/dist
- npm install vuepress -g
- echo "Install done!"
script:
- cd docs && npm run build
- echo "Build done!"
after_success:
- cd .vuepress/dist/
- travis_wait scp -r * ubuntu@18.191.12.61:/nch-docs/
branches:
  only:
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_4b1c888bc596_key -iv $encrypted_4b1c888bc596_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
addons:
  ssh_known_hosts: 18.191.12.61
